package com.antec.model.entity;

public class Areamaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areaMaster.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areaMaster.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areaMaster.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column areaMaster.regintype
     *
     * @mbggenerated
     */
    private String regintype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areaMaster.id
     *
     * @return the value of areaMaster.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areaMaster.id
     *
     * @param id the value for areaMaster.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areaMaster.parentid
     *
     * @return the value of areaMaster.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areaMaster.parentid
     *
     * @param parentid the value for areaMaster.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areaMaster.name
     *
     * @return the value of areaMaster.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areaMaster.name
     *
     * @param name the value for areaMaster.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column areaMaster.regintype
     *
     * @return the value of areaMaster.regintype
     *
     * @mbggenerated
     */
    public String getRegintype() {
        return regintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column areaMaster.regintype
     *
     * @param regintype the value for areaMaster.regintype
     *
     * @mbggenerated
     */
    public void setRegintype(String regintype) {
        this.regintype = regintype;
    }
}