package com.antec.model.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Checkedcollectinfo extends CheckedcollectinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.modifyKbn
     *
     * @mbggenerated
     */
    private String modifykbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.modifiyUrl
     *
     * @mbggenerated
     */
    private String modifiyurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.occurDate
     *
     * @mbggenerated
     */
    private Date occurdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.eventSummary
     *
     * @mbggenerated
     */
    private String eventsummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.eventAddressId
     *
     * @mbggenerated
     */
    private Integer eventaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.pickedAddress
     *
     * @mbggenerated
     */
    private String pickedaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.longitude
     *
     * @mbggenerated
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.latitude
     *
     * @mbggenerated
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.credibility
     *
     * @mbggenerated
     */
    private Integer credibility;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.modifyKbn
     *
     * @return the value of checkedCollectInfo.modifyKbn
     *
     * @mbggenerated
     */
    public String getModifykbn() {
        return modifykbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.modifyKbn
     *
     * @param modifykbn the value for checkedCollectInfo.modifyKbn
     *
     * @mbggenerated
     */
    public void setModifykbn(String modifykbn) {
        this.modifykbn = modifykbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.modifiyUrl
     *
     * @return the value of checkedCollectInfo.modifiyUrl
     *
     * @mbggenerated
     */
    public String getModifiyurl() {
        return modifiyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.modifiyUrl
     *
     * @param modifiyurl the value for checkedCollectInfo.modifiyUrl
     *
     * @mbggenerated
     */
    public void setModifiyurl(String modifiyurl) {
        this.modifiyurl = modifiyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.occurDate
     *
     * @return the value of checkedCollectInfo.occurDate
     *
     * @mbggenerated
     */
    public Date getOccurdate() {
        return occurdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.occurDate
     *
     * @param occurdate the value for checkedCollectInfo.occurDate
     *
     * @mbggenerated
     */
    public void setOccurdate(Date occurdate) {
        this.occurdate = occurdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.eventSummary
     *
     * @return the value of checkedCollectInfo.eventSummary
     *
     * @mbggenerated
     */
    public String getEventsummary() {
        return eventsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.eventSummary
     *
     * @param eventsummary the value for checkedCollectInfo.eventSummary
     *
     * @mbggenerated
     */
    public void setEventsummary(String eventsummary) {
        this.eventsummary = eventsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.eventAddressId
     *
     * @return the value of checkedCollectInfo.eventAddressId
     *
     * @mbggenerated
     */
    public Integer getEventaddressid() {
        return eventaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.eventAddressId
     *
     * @param eventaddressid the value for checkedCollectInfo.eventAddressId
     *
     * @mbggenerated
     */
    public void setEventaddressid(Integer eventaddressid) {
        this.eventaddressid = eventaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.pickedAddress
     *
     * @return the value of checkedCollectInfo.pickedAddress
     *
     * @mbggenerated
     */
    public String getPickedaddress() {
        return pickedaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.pickedAddress
     *
     * @param pickedaddress the value for checkedCollectInfo.pickedAddress
     *
     * @mbggenerated
     */
    public void setPickedaddress(String pickedaddress) {
        this.pickedaddress = pickedaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.longitude
     *
     * @return the value of checkedCollectInfo.longitude
     *
     * @mbggenerated
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.longitude
     *
     * @param longitude the value for checkedCollectInfo.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.latitude
     *
     * @return the value of checkedCollectInfo.latitude
     *
     * @mbggenerated
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.latitude
     *
     * @param latitude the value for checkedCollectInfo.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.credibility
     *
     * @return the value of checkedCollectInfo.credibility
     *
     * @mbggenerated
     */
    public Integer getCredibility() {
        return credibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.credibility
     *
     * @param credibility the value for checkedCollectInfo.credibility
     *
     * @mbggenerated
     */
    public void setCredibility(Integer credibility) {
        this.credibility = credibility;
    }
}