package com.antec.model.entity;

public class CheckedcollectinfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkedCollectInfo.collectInfoId
     *
     * @mbggenerated
     */
    private Integer collectinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.id
     *
     * @return the value of checkedCollectInfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.id
     *
     * @param id the value for checkedCollectInfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkedCollectInfo.collectInfoId
     *
     * @return the value of checkedCollectInfo.collectInfoId
     *
     * @mbggenerated
     */
    public Integer getCollectinfoid() {
        return collectinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkedCollectInfo.collectInfoId
     *
     * @param collectinfoid the value for checkedCollectInfo.collectInfoId
     *
     * @mbggenerated
     */
    public void setCollectinfoid(Integer collectinfoid) {
        this.collectinfoid = collectinfoid;
    }
}