package com.antec.model.entity;

public class Checkkeywordrelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkKeywordRelation.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checkKeywordRelation.checkedId
     *
     * @mbggenerated
     */
    private Integer checkedid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkKeywordRelation.id
     *
     * @return the value of checkKeywordRelation.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkKeywordRelation.id
     *
     * @param id the value for checkKeywordRelation.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checkKeywordRelation.checkedId
     *
     * @return the value of checkKeywordRelation.checkedId
     *
     * @mbggenerated
     */
    public Integer getCheckedid() {
        return checkedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checkKeywordRelation.checkedId
     *
     * @param checkedid the value for checkKeywordRelation.checkedId
     *
     * @mbggenerated
     */
    public void setCheckedid(Integer checkedid) {
        this.checkedid = checkedid;
    }
}