package com.antec.model.entity;

public class Collectinitinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.kbn
     *
     * @mbggenerated
     */
    private String kbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.reportdate
     *
     * @mbggenerated
     */
    private String reportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collectinitInfo.checkflg
     *
     * @mbggenerated
     */
    private String checkflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.id
     *
     * @return the value of collectinitInfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.id
     *
     * @param id the value for collectinitInfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.kbn
     *
     * @return the value of collectinitInfo.kbn
     *
     * @mbggenerated
     */
    public String getKbn() {
        return kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.kbn
     *
     * @param kbn the value for collectinitInfo.kbn
     *
     * @mbggenerated
     */
    public void setKbn(String kbn) {
        this.kbn = kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.title
     *
     * @return the value of collectinitInfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.title
     *
     * @param title the value for collectinitInfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.url
     *
     * @return the value of collectinitInfo.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.url
     *
     * @param url the value for collectinitInfo.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.reportdate
     *
     * @return the value of collectinitInfo.reportdate
     *
     * @mbggenerated
     */
    public String getReportdate() {
        return reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.reportdate
     *
     * @param reportdate the value for collectinitInfo.reportdate
     *
     * @mbggenerated
     */
    public void setReportdate(String reportdate) {
        this.reportdate = reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collectinitInfo.checkflg
     *
     * @return the value of collectinitInfo.checkflg
     *
     * @mbggenerated
     */
    public String getCheckflg() {
        return checkflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collectinitInfo.checkflg
     *
     * @param checkflg the value for collectinitInfo.checkflg
     *
     * @mbggenerated
     */
    public void setCheckflg(String checkflg) {
        this.checkflg = checkflg;
    }
}