package com.antec.model.entity;

import java.util.Date;

public class Eventaddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.country
     *
     * @mbggenerated
     */
    private Integer country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.province
     *
     * @mbggenerated
     */
    private Integer province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.city
     *
     * @mbggenerated
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.postCode
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.createId
     *
     * @mbggenerated
     */
    private String createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.updid
     *
     * @mbggenerated
     */
    private String updid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventAddress.updDate
     *
     * @mbggenerated
     */
    private Date upddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.id
     *
     * @return the value of eventAddress.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.id
     *
     * @param id the value for eventAddress.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.country
     *
     * @return the value of eventAddress.country
     *
     * @mbggenerated
     */
    public Integer getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.country
     *
     * @param country the value for eventAddress.country
     *
     * @mbggenerated
     */
    public void setCountry(Integer country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.province
     *
     * @return the value of eventAddress.province
     *
     * @mbggenerated
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.province
     *
     * @param province the value for eventAddress.province
     *
     * @mbggenerated
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.city
     *
     * @return the value of eventAddress.city
     *
     * @mbggenerated
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.city
     *
     * @param city the value for eventAddress.city
     *
     * @mbggenerated
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.area
     *
     * @return the value of eventAddress.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.area
     *
     * @param area the value for eventAddress.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.postCode
     *
     * @return the value of eventAddress.postCode
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.postCode
     *
     * @param postcode the value for eventAddress.postCode
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.createId
     *
     * @return the value of eventAddress.createId
     *
     * @mbggenerated
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.createId
     *
     * @param createid the value for eventAddress.createId
     *
     * @mbggenerated
     */
    public void setCreateid(String createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.createDate
     *
     * @return the value of eventAddress.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.createDate
     *
     * @param createdate the value for eventAddress.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.updid
     *
     * @return the value of eventAddress.updid
     *
     * @mbggenerated
     */
    public String getUpdid() {
        return updid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.updid
     *
     * @param updid the value for eventAddress.updid
     *
     * @mbggenerated
     */
    public void setUpdid(String updid) {
        this.updid = updid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventAddress.updDate
     *
     * @return the value of eventAddress.updDate
     *
     * @mbggenerated
     */
    public Date getUpddate() {
        return upddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventAddress.updDate
     *
     * @param upddate the value for eventAddress.updDate
     *
     * @mbggenerated
     */
    public void setUpddate(Date upddate) {
        this.upddate = upddate;
    }
}