package com.antec.model.entity;

import java.util.Date;

public class Eventkeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventKeyword.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventKeyword.kbn
     *
     * @mbggenerated
     */
    private String kbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventKeyword.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventKeyword.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventKeyword.id
     *
     * @return the value of eventKeyword.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventKeyword.id
     *
     * @param id the value for eventKeyword.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventKeyword.kbn
     *
     * @return the value of eventKeyword.kbn
     *
     * @mbggenerated
     */
    public String getKbn() {
        return kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventKeyword.kbn
     *
     * @param kbn the value for eventKeyword.kbn
     *
     * @mbggenerated
     */
    public void setKbn(String kbn) {
        this.kbn = kbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventKeyword.keyword
     *
     * @return the value of eventKeyword.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventKeyword.keyword
     *
     * @param keyword the value for eventKeyword.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventKeyword.createDate
     *
     * @return the value of eventKeyword.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventKeyword.createDate
     *
     * @param createdate the value for eventKeyword.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}