package com.antec.model.entity;

import java.util.Date;

public class Locationkeyword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locationKeyword.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locationKeyword.word
     *
     * @mbggenerated
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column locationKeyword.createDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locationKeyword.id
     *
     * @return the value of locationKeyword.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locationKeyword.id
     *
     * @param id the value for locationKeyword.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locationKeyword.word
     *
     * @return the value of locationKeyword.word
     *
     * @mbggenerated
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locationKeyword.word
     *
     * @param word the value for locationKeyword.word
     *
     * @mbggenerated
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column locationKeyword.createDate
     *
     * @return the value of locationKeyword.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column locationKeyword.createDate
     *
     * @param createdate the value for locationKeyword.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}