package com.antec.model.mapper;

import com.antec.model.entity.Checkkeywordrelation;
import com.antec.model.entity.CheckkeywordrelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckkeywordrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int countByExample(CheckkeywordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int deleteByExample(CheckkeywordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int insert(Checkkeywordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int insertSelective(Checkkeywordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    List<Checkkeywordrelation> selectByExample(CheckkeywordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    Checkkeywordrelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Checkkeywordrelation record, @Param("example") CheckkeywordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Checkkeywordrelation record, @Param("example") CheckkeywordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Checkkeywordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkKeywordRelation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Checkkeywordrelation record);
}