package com.antec.model.mapper;

import com.antec.model.entity.Checkedcollectinfo;
import com.antec.model.entity.CheckedcollectinfoExample;
import com.antec.model.entity.CheckedcollectinfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CheckedcollectinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int countByExample(CheckedcollectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int deleteByExample(CheckedcollectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CheckedcollectinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int insert(Checkedcollectinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int insertSelective(Checkedcollectinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    List<Checkedcollectinfo> selectByExample(CheckedcollectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    Checkedcollectinfo selectByPrimaryKey(CheckedcollectinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Checkedcollectinfo record, @Param("example") CheckedcollectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Checkedcollectinfo record, @Param("example") CheckedcollectinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Checkedcollectinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkedCollectInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Checkedcollectinfo record);
}