package com.antec.model.mapper;

import com.antec.model.entity.Collectinitinfo;
import com.antec.model.entity.CollectinitinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectinitinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int countByExample(CollectinitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int deleteByExample(CollectinitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int insert(Collectinitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int insertSelective(Collectinitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    List<Collectinitinfo> selectByExample(CollectinitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    Collectinitinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Collectinitinfo record, @Param("example") CollectinitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Collectinitinfo record, @Param("example") CollectinitinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Collectinitinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collectinitInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Collectinitinfo record);
}