package com.antec.model.mapper;

import com.antec.model.entity.Eventaddress;
import com.antec.model.entity.EventaddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int countByExample(EventaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int deleteByExample(EventaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int insert(Eventaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int insertSelective(Eventaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    List<Eventaddress> selectByExample(EventaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    Eventaddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Eventaddress record, @Param("example") EventaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Eventaddress record, @Param("example") EventaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Eventaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eventAddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Eventaddress record);
}