package com.antec.model.mapper;

import com.antec.model.entity.Locationkeyword;
import com.antec.model.entity.LocationkeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationkeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int countByExample(LocationkeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int deleteByExample(LocationkeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int insert(Locationkeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int insertSelective(Locationkeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    List<Locationkeyword> selectByExample(LocationkeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    Locationkeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Locationkeyword record, @Param("example") LocationkeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Locationkeyword record, @Param("example") LocationkeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Locationkeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locationKeyword
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Locationkeyword record);
}